# Generated by Django 6.1.1 on 2026-10-03 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMochila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_loja', models.IntegerField(help_text='ID do item no catálogo da loja')),
                ('nome_item', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mochila', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'item_id_loja')},
            },
        ),
    ]
