# Generated by Django 6.1.1 on 2026-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMochila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.PositiveBigIntegerField(db_index=True)),
                ('item_id_loja', models.IntegerField(help_text='ID do item no catálogo da loja')),
                ('nome_item', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('usuario_id', 'item_id_loja')},
            },
        ),
    ]
