# Generated by Django 6.1.1 on 2026-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do item')),
                ('estoque', models.PositiveBigIntegerField(default=0)),
                ('preco_compra', models.DecimalField(decimal_places=2, help_text='Valor pago para compra o item', max_digits=10)),
            ],
        ),
    ]
