# Generated by Django 6.1.1 on 2026-10-02 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do item', null=True),
        ),
        migrations.CreateModel(
            name='Aventureiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moedas_draconicas', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aventureiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=6)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.TimeField(auto_now_add=True)),
                ('aventureiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.aventureiro')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercio.item')),
            ],
        ),
    ]
